### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by violaso** [INDAPlus21/murnion-task-15#1]
**Well done almost Felix!**

I miss your Kattis proof as well as a tree structure.

Contact me on submission.

**Comment by abdbla** [comment]
submittad, med bevis och träd struktur. strukturen är utan tvekan en av de fulaste self-balancing trees man kan skapa, men den funkar, på något sätt och vis. det tycker jag, personligen, är ganska otroligt.

jag vet inte om du vill att jag ska kontakta dig på discord? vi får väl se imorgon.

**Comment by violaso** [comment]
Tack!
